// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

// Subject is a school subject, like math or biology
type Subject struct {
	Code *string `json:"code"`
	Name *string `json:"name"`
}
