# Build
FROM golang:1.15-alpine as builder

# For compiling dempendancies
RUN apk update && \
    apk upgrade && \
    apk add gcc g++ musl-dev git curl ca-certificates

# Install wait-for for docker-compose
# so that we can wait for the database to
# startup if we need to.
RUN curl -s https://raw.githubusercontent.com/eficode/wait-for/master/wait-for \
    -o /usr/local/bin/wait-for && \
  chmod +x /usr/local/bin/wait-for

# Cache Go dependancies
# Module download will be cached if
# go.mod and go.sum don't change
COPY go.mod /app/tmp/go.mod
COPY go.sum /app/tmp/go.sum
WORKDIR /app/tmp
RUN go mod download

COPY . /app/src
WORKDIR /app/src

RUN mkdir /app/tests && \
    for pkg in $(go list ./...); do \
        go test -c $pkg -o /app/tests/$(basename $pkg).test; \
    done
